### ISSUE TITLE
MS4 Feedback

### ISSUE THREAD

**Issue by sairafurqan** [ubco-W2022T2-data301/project-group-group36#1]
## Feedback for Group 36

1. Notes from [Saira] on Feedback on the analysis:

Analysis 1:

- [x] Add conclusion to your Notebook.
- [x] move method chaining to .py file

Analysis 2:

- [x] Add conclusion to your Notebook.
- [x] move method chaining to .py file

Analysis 3:

- [x] Add conclusion to your Notebook.
- [x] move method chaining to .py file

## Contracted Grade

1. What is your contracted grade?

- A+

2. Are you on track to satisfy all the requirements of your contracted grade?

- No, you should consider contracting for a lower grade to ensure you meet a high level of quality on all the work you submit. [Please review the details of each contracted grade here](https://firas.moosvi.com/courses/data301/2022_WT2/project/introduction.html) and if you have questions, come see the instructor or the Project TAs for more details.

**Comment by LilDA00** [comment]
I think we will change our contracted grade to an A as we have reasonably met all of the requirements.
