### ISSUE TITLE
Urgent: Few things outstanding to get to an A

### ISSUE THREAD

**Issue by sairafurqan** [ubco-W2022T2-data301/project-group-group36#2]
Hello,

I was going through your project and you have met all but two of the criteria for an A+. One of the things is really easy, and the other one is one member dashboard is missing. 

Here are the two things missing:

- [x] Issues aren't closed (though all the tasks are completed) ; effective use of issues requires all resolved issues to be closed.
- [x] Dashboard file is missing for Kobe Brunetti 

Please fix these so that I can grade your submission.

Thanks,

**Comment by KobeBrunetti** [comment]
My bad, I added the dashboard originally but under the wrong file. It's in the correct file now!
